org.gradle.java.home=C:/Users/yyy/.gradle/jdks/eclipse_adoptium-21-amd64-windows/jdk-21.0.9+10
org.gradle.jvmargs=-Dfile.encoding=UTF-8

## Proxy
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897

## Environment Properties
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
neo_version=21.11.42
neo_version_range=[21.11,)
loader_version_range=[4,)

## Mod Properties
mod_id=craftablecapes
mod_name=Craftable Capes
mod_license=GPL-3.0
mod_version=1.0.0
mod_group_id=com.craftablecapes
mod_authors=Ryhon (Ported by You)
mod_description=Craft and wear any cape you want! Ported to NeoForge with Curios API support.

## Dependency Versions
curios_version=MPGhs9Rw
